[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/plugins/iceberg.rc.vim
'''

# ==========================================================
# basic
# ==========================================================

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
source ~/.config/nvim/plugins/nerdcomenter.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugins/anzu.rc.vim
'''

[[plugins]]
repo = 'LeafCage/yankround.vim.git'
hook_add = '''
source ~/.config/nvim/plugins/yankround.rc.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'milkypostman/vim-togglelist'
hook_add = '''
nmap <script> <silent> <C-l> :call ToggleLocationList()<CR>
nmap <script> <silent> <C-q> :call ToggleQuickfixList()<CR> " Bug: not work in neovim
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'osyo-manga/vim-over'


# ==========================================================
# linter
# ==========================================================

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.rc.vim
'''

# ==========================================================
# filer
# ==========================================================

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
map <C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# ==========================================================
# powerline
# ==========================================================

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive']
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
hook_add = '''
let g:airline_theme='luna'
'''

[[plugins]]
repo = 'gcmt/taboo.vim'
depends = 'vim-airline'
hook_add = '''
if !has('nvim')
  set guioptions-=e
  set sessionoptions+=tabpages,globals
endif
let g:taboo_tab_format=' t%N %f%m '
let g:taboo_tabline = 0
'''

# ==========================================================
# terminal
# ==========================================================

[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/neoterm.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimshell'
if = "!has('nvim')"
hook_add = '''
source ~/.config/nvim/plugins/vimshell.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = "!has('nvim')"
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'

# ==========================================================
# for vim8 compatible neovim
# ==========================================================

[[plugins]]
repo = "roxma/vim-hug-neovim-rpc"
if = "!has('nvim')"

[[plugins]]
repo = "roxma/nvim-yarp"
if = "!has('nvim')"

# ==========================================================
# LSP
# ==========================================================

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
build = 'bash install.sh'
rev = 'next'
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
    \ 'vue': ['vls'],
    \ 'rust': ['rls'],
    \ 'typescript': ['javascript-typescript-stdio'],
    \ 'javascript': ['javascript-typescript-stdio'],
    \ 'javascript.jsx': ['javascript-typescript-stdio'],
    \ 'cpp': ['clangd'],
    \ }

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
" Or map each action separately
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>

nnoremap <silent> <F3> :call LanguageClient_textDocument_formatting()
'''

#[[plugins]]
#repo = 'Shougo/context_filetype.vim'
